name: Close n Merge

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Catch state
        id: pr
        run: |
          echo "PUSH_IMAGE=TRUE" >> $GITHUB_OUTPUT
          if "${{ github.event.pull_request.merged }}" eq "false"
          then
            echo "PUSH_IMAGE=FALSE" >> $GITHUB_OUTPUT
          fi
      - name: Dbg
        run: |
          echo ${{ steps.pr.outputs.PUSH_IMAGE }}
